// Code generated by goctl. DO NOT EDIT!
// Source: stock.proto

package server

import (
	"context"

	"gozerodtm/stock-srv/internal/logic"
	"gozerodtm/stock-srv/internal/svc"
	"gozerodtm/stock-srv/pb"
)

type StockServer struct {
	svcCtx *svc.ServiceContext
}

func NewStockServer(svcCtx *svc.ServiceContext) *StockServer {
	return &StockServer{
		svcCtx: svcCtx,
	}
}

func (s *StockServer) Deduct(ctx context.Context, in *pb.DecuctReq) (*pb.DeductResp, error) {
	l := logic.NewDeductLogic(ctx, s.svcCtx)
	return l.Deduct(in)
}

func (s *StockServer) DeductRollback(ctx context.Context, in *pb.DecuctReq) (*pb.DeductResp, error) {
	l := logic.NewDeductRollbackLogic(ctx, s.svcCtx)
	return l.DeductRollback(in)
}
