// Code generated by goctl. DO NOT EDIT.
package types

type QuickCreateReq struct {
	UserId  int64 `json:"userId"`
	GoodsId int64 `json:"goodsId"`
	Num     int64 `json:"num"`
}

type QuickCreateResp struct {
}
